"""Domain feed fetching and processing for DNS sinkhole."""

import asyncio
import re
from datetime import datetime
from pathlib import Path
from typing import List, Set, Optional

import aiohttp
import structlog

from meshwall.config import Config

logger = structlog.get_logger()


class DomainFeedUpdater:
    """Download, parse, deduplicate, and apply domain blocklists for dnsmasq."""

    def __init__(self, config: Config, debug: bool = False) -> None:
        self.config = config
        self.debug = debug
        self.session: Optional[aiohttp.ClientSession] = None
        self.temp_dir = config.data_dir / "temp"
        self.temp_dir.mkdir(exist_ok=True)

    async def run(self, verbose: bool = False) -> None:
        """Main update routine for domain feeds."""
        logger.info("Starting domain feed update")
        print("Starting domain feed update...")

        timeout = aiohttp.ClientTimeout(
            total=self.config.fetch_timeout,
            connect=10,
            sock_read=15,
        )

        async with aiohttp.ClientSession(timeout=timeout) as session:
            self.session = session
            tasks = [self._fetch_with_verbose(url, verbose) for url in self.config.domain_feed_urls]
            results = await asyncio.gather(*tasks, return_exceptions=True)

        all_domains: Set[str] = set()
        for i, res in enumerate(results):
            url = self.config.domain_feed_urls[i]
            if isinstance(res, Exception):
                logger.error("Domain feed fetch failed", url=url, error=str(res))
                print(f"✗ {url}: {res}")
            elif res:
                all_domains.update(res)
                print(f"✓ {url}: {len(res)} domains")

        whitelist = self._load_domain_whitelist()
        all_domains.difference_update(whitelist)

        domain_list = list(all_domains)[: self.config.max_domain_entries]
        logger.info("Processed domain feeds", total_domains=len(domain_list))
        print(f"Total unique domains after dedup: {len(domain_list)}")

        if not domain_list:
            print("No domains to block. Check feeds or network.")
            return

        await self._write_dnsmasq_config(domain_list)

        if not getattr(self.config, 'dry_run', False):
            await self._reload_dnsmasq()
        else:
            print(f"Dry run: would write {len(domain_list)} domains to dnsmasq config")

        logger.info("Domain feed update complete")
        print("Domain update complete.")

    async def _fetch_with_verbose(self, url: str, verbose: bool) -> Set[str]:
        if verbose:
            print(f"Fetching domain feed {url}...")
        try:
            return await self._fetch_and_parse(url)
        except Exception as e:
            raise e

    async def _fetch_and_parse(self, url: str) -> Set[str]:
        try:
            async with self.session.get(url) as resp:  # type: ignore
                if resp.status != 200:
                    logger.warning("Domain feed fetch failed", url=url, status=resp.status)
                    return set()
                content = await resp.text()
        except asyncio.TimeoutError:
            logger.error("Domain feed fetch timeout", url=url)
            return set()
        except aiohttp.ClientError as e:
            logger.error("Domain feed fetch client error", url=url, error=str(e))
            return set()
        except Exception as e:
            logger.error("Domain feed fetch unexpected error", url=url, error=str(e))
            return set()

        domains = set()
        for line in content.splitlines():
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            parts = line.split()
            if len(parts) >= 2 and (parts[0] == "0.0.0.0" or parts[0] == "127.0.0.1"):
                domain = parts[1]
                if re.match(r"^[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$", domain):
                    domains.add(domain)
        return domains

    def _load_domain_whitelist(self) -> Set[str]:
        whitelist: Set[str] = set()
        whitelist_file = self.config.data_dir / "domain_whitelist.txt"
        if whitelist_file.exists():
            for line in whitelist_file.read_text().splitlines():
                line = line.strip()
                if line and not line.startswith("#"):
                    whitelist.add(line)
        return whitelist

    async def _write_dnsmasq_config(self, domains: List[str]) -> None:
        config_path = self.config.dnsmasq_config
        config_path.parent.mkdir(parents=True, exist_ok=True)
        
        lines = [
            "# Generated by MeshWall - DO NOT EDIT MANUALLY\n",
            f"# Updated: {datetime.utcnow().isoformat()}\n\n"
        ]
        for domain in domains:
            lines.append(f"address=/{domain}/0.0.0.0\n")
            lines.append(f"address=/{domain}/::\n")

        import aiofiles
        async with aiofiles.open(config_path, "w") as f:
            await f.writelines(lines)

    async def _reload_dnsmasq(self) -> None:
        import subprocess
        try:
            subprocess.run(["systemctl", "reload", "dnsmasq"], check=True, timeout=10)
            print("dnsmasq reloaded successfully.")
        except Exception as e:
            logger.error("Failed to reload dnsmasq", error=str(e))
            print(f"Warning: Failed to reload dnsmasq: {e}")